name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create Azure Compute Cluster
      run: az ml compute create -n cluster1 --type amlcompute --min-instances 0 --max-instances 4 --resource-group resourceGrp1 --workspace-name workspace1
    - name: Run Azure ML job
      run: az ml job create --file src/job.yml --resource-group resourceGrp1 --workspace-name workspace1


